app_schema={
    "/TXLife": {
        "/TXLife/TXLifeRequest/OLifE/Holding/@id": "Holding_id",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/@id": "Attachment_id",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentBasicType": "Attachment_AttachmentBasicType",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentBasicType/@tc": "AttachmentBasicType_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentData": "Attachment_AttachmentData",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentData/@tc": "AttachmentData_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentLocation": "Attachment_AttachmentLocation",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentLocation/@tc": "AttachmentLocation_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentType": "Attachment_AttachmentType",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/AttachmentType/@tc": "AttachmentType_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/Description": "Attachment_Description",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/MimeTypeTC": "Attachment_MimeTypeTC",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/MimeTypeTC/@tc": "MimeTypeTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/TransferEncodingTypeTC": "Attachment_TransferEncodingTypeTC",
        "/TXLife/TXLifeRequest/OLifE/Holding/Attachment/TransferEncodingTypeTC/@tc": "TransferEncodingTypeTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/HoldingStatus": "Holding_HoldingStatus",
        "/TXLife/TXLifeRequest/OLifE/Holding/HoldingStatus/@tc": "HoldingStatus_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/HoldingTypeCode": "Holding_HoldingTypeCode",
        "/TXLife/TXLifeRequest/OLifE/Holding/HoldingTypeCode/@tc": "HoldingTypeCode_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/@CarrierPartyID": "Policy_CarrierPartyID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/@id": "Policy_id",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/ApplicationJurisdiction": "ApplicationInfo_ApplicationJurisdiction",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/ApplicationJurisdiction/@tc": "ApplicationJurisdiction_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/DisclosureInd": "ApplicationInfo_DisclosureInd",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/DisclosureInd/@tc": "DisclosureInd_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/PrefLanguage": "ApplicationInfo_PrefLanguage",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/PrefLanguage/@tc": "PrefLanguage_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ApplicationInfo/TrackingID": "ApplicationInfo_TrackingID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/CarrierCode": "Policy_CarrierCode",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/Life/FaceAmt": "Life_FaceAmt",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/PlanName": "Policy_PlanName",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/PolNumber": "Policy_PolNumber",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ProductCode": "Policy_ProductCode",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ProductType": "Policy_ProductType",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/ProductType/@tc": "ProductType_tc",
        "/TXLife/TXLifeRequest/OLifE/SourceInfo/CreationDate": "SourceInfo_CreationDate",
        "/TXLife/TXLifeRequest/OLifE/SourceInfo/FileControlID": "SourceInfo_FileControlID",
        "/TXLife/TXLifeRequest/OLifE/SourceInfo/SourceInfoName": "SourceInfo_SourceInfoName",
        "/TXLife/TXLifeRequest/TestIndicator": "TXLifeRequest_TestIndicator",
        "/TXLife/TXLifeRequest/TestIndicator/@tc": "TestIndicator_tc",
        "/TXLife/TXLifeRequest/TransExeDate": "TXLifeRequest_TransExeDate",
        "/TXLife/TXLifeRequest/TransExeTime": "TXLifeRequest_TransExeTime",
        "/TXLife/TXLifeRequest/TransRefGUID": "TXLifeRequest_TransRefGUID",
        "/TXLife/TXLifeRequest/TransType": "TXLifeRequest_TransType",
        "/TXLife/TXLifeRequest/TransType/@tc": "TransType_tc",
        "/TXLife/UserAuthRequest/UserLoginName": "UserAuthRequest_UserLoginName",
        "/TXLife/UserAuthRequest/UserPswd/CryptType": "UserPswd_CryptType",
        "/TXLife/UserAuthRequest/UserPswd/Pswd": "UserPswd_Pswd",
        "/TXLife/UserAuthRequest/VendorApp/AppName": "VendorApp_AppName",
        "/TXLife/UserAuthRequest/VendorApp/AppVer": "VendorApp_AppVer",
        "/TXLife/UserAuthRequest/VendorApp/VendorName": "VendorApp_VendorName",
        "/TXLife/UserAuthRequest/VendorApp/VendorName/@VendorCode": "VendorName_VendorCode"
    },
    "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo": {
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/@AppliesToPartyID": "AppliesToPartyID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/@FulfillerPartyID": "FulfillerPartyID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/@RequesterPartyID": "RequesterPartyID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/@RequestorContactPartyID": "RequestorContactPartyID",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/@id": "id",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/@id": "Attachment_id",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentBasicType": "Attachment_AttachmentBasicType",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentBasicType/@tc": "AttachmentBasicType_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentData": "Attachment_AttachmentData",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentData/@tc": "AttachmentData_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentLocation": "Attachment_AttachmentLocation",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentLocation/@tc": "AttachmentLocation_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentType": "Attachment_AttachmentType",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/AttachmentType/@tc": "AttachmentType_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/Description": "Attachment_Description",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/MimeTypeTC": "Attachment_MimeTypeTC",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/MimeTypeTC/@tc": "MimeTypeTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/TransferEncodingTypeTC": "Attachment_TransferEncodingTypeTC",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Attachment/TransferEncodingTypeTC/@tc": "TransferEncodingTypeTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Priority": "Priority",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/Priority/@tc": "Priority_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/ReqCode": "ReqCode",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/ReqCode/@tc": "ReqCode_tc",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequestedDate": "RequestedDate",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequestedScheduleDate": "RequestedScheduleDate",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequestedScheduleTimeEnd": "RequestedScheduleTimeEnd",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequestedScheduleTimeStart": "RequestedScheduleTimeStart",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequirementDetails": "RequirementDetails",
        "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo/RequirementInfoUniqueID": "RequirementInfoUniqueID"
    },
    "/TXLife/TXLifeRequest/OLifE/Party": {
        "/TXLife/TXLifeRequest/OLifE/Party/@id": "id",
        "/TXLife/TXLifeRequest/OLifE/Party/EMailAddress/@id": "EMailAddress_id",
        "/TXLife/TXLifeRequest/OLifE/Party/EMailAddress/AddrLine": "EMailAddress_AddrLine",
        "/TXLife/TXLifeRequest/OLifE/Party/EMailAddress/EMailType": "EMailAddress_EMailType",
        "/TXLife/TXLifeRequest/OLifE/Party/EMailAddress/EMailType/@tc": "EMailType_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/FullName": "FullName",
        "/TXLife/TXLifeRequest/OLifE/Party/GovtID": "GovtID",
        "/TXLife/TXLifeRequest/OLifE/Party/GovtIDTC": "GovtIDTC",
        "/TXLife/TXLifeRequest/OLifE/Party/GovtIDTC/@tc": "GovtIDTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Organization/ACORDVendorCode": "Organization_ACORDVendorCode",
        "/TXLife/TXLifeRequest/OLifE/Party/Organization/AbbrName": "Organization_AbbrName",
        "/TXLife/TXLifeRequest/OLifE/Party/Organization/OrgCode": "Organization_OrgCode",
        "/TXLife/TXLifeRequest/OLifE/Party/PartyTypeCode": "PartyTypeCode",
        "/TXLife/TXLifeRequest/OLifE/Party/PartyTypeCode/@tc": "PartyTypeCode_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/BirthDate": "Person_BirthDate",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/DOBEstimated": "Person_DOBEstimated",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/DOBEstimated/@tc": "DOBEstimated_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/DriversLicenseNum": "Person_DriversLicenseNum",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/DriversLicenseState": "Person_DriversLicenseState",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/DriversLicenseState/@tc": "DriversLicenseState_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/FirstName": "Person_FirstName",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/Gender": "Person_Gender",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/Gender/@tc": "Gender_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/LastName": "Person_LastName",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/MarStat": "Person_MarStat",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/MarStat/@tc": "MarStat_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/MiddleName": "Person_MiddleName",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/NickName": "Person_NickName",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/Prefix": "Person_Prefix",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/SmokerStat": "Person_SmokerStat",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/SmokerStat/@tc": "SmokerStat_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Person/Suffix": "Person_Suffix",
        "/TXLife/TXLifeRequest/OLifE/Party/Producer/CarrierAppointment/CompanyProducerID": "CarrierAppointment_CompanyProducerID",
        "/TXLife/TXLifeRequest/OLifE/Party/ResidenceZip": "ResidenceZip"
    },
    "/TXLife/TXLifeRequest/OLifE/Party/Address": {
        "/TXLife/TXLifeRequest/OLifE/Party/Address/@id": "id",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/AddressStateTC": "AddressStateTC",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/AddressStateTC/@tc": "AddressStateTC_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/AddressTypeCode": "AddressTypeCode",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/AddressTypeCode/@tc": "AddressTypeCode_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/City": "City",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/Line1": "Line1",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/Line2": "Line2",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/PrefAddr": "PrefAddr",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/PrefAddr/@tc": "PrefAddr_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Address/Zip": "Zip"
    },
    "/TXLife/TXLifeRequest/OLifE/Party/Phone": {
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/@id": "id",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/AreaCode": "AreaCode",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/BestTimeToCallFrom": "BestTimeToCallFrom",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/BestTimeToCallTo": "BestTimeToCallTo",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/DialNumber": "DialNumber",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/Ext": "Ext",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/PhoneTypeCode": "PhoneTypeCode",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/PhoneTypeCode/@tc": "PhoneTypeCode_tc",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/PrefPhone": "PrefPhone",
        "/TXLife/TXLifeRequest/OLifE/Party/Phone/PrefPhone/@tc": "PrefPhone_tc"
    },
    "/TXLife/TXLifeRequest/OLifE/Relation": {
        "/TXLife/TXLifeRequest/OLifE/Relation/@OriginatingObjectID": "OriginatingObjectID",
        "/TXLife/TXLifeRequest/OLifE/Relation/@RelatedObjectID": "RelatedObjectID",
        "/TXLife/TXLifeRequest/OLifE/Relation/@id": "id",
        "/TXLife/TXLifeRequest/OLifE/Relation/OriginatingObjectType": "OriginatingObjectType",
        "/TXLife/TXLifeRequest/OLifE/Relation/OriginatingObjectType/@tc": "OriginatingObjectType_tc",
        "/TXLife/TXLifeRequest/OLifE/Relation/RelatedObjectType": "RelatedObjectType",
        "/TXLife/TXLifeRequest/OLifE/Relation/RelatedObjectType/@tc": "RelatedObjectType_tc",
        "/TXLife/TXLifeRequest/OLifE/Relation/RelationRoleCode": "RelationRoleCode",
        "/TXLife/TXLifeRequest/OLifE/Relation/RelationRoleCode/@tc": "RelationRoleCode_tc"
    }
}

relationships = {
    "/TXLife": {
         "childrens": [
              "/TXLife/TXLifeRequest/OLifE/Relation",
              "/TXLife/TXLifeRequest/OLifE/Party",
              "/TXLife/TXLifeRequest/OLifE/Holding/Policy/RequirementInfo"
         ],
         "parent": None
    },
    "/TXLife/TXLifeRequest/OLifE/Party": {
         "childrens": [
              "/TXLife/TXLifeRequest/OLifE/Party/Address",
              "/TXLife/TXLifeRequest/OLifE/Party/Phone"
          ],
         "parent": "/TXLife"
    }
}

namespace = '{http://ACORD.org/Standards/Life/2}'
